name: simeng-benchmarks
description: runs simeng benchmarks

inputs:
  BENCHMARK_BRANCH:
    description: name of the branch on the benchmark repo you want to checkout 
    required: true
  OS:
    description: docker image name
    required: true
  PAT:
    description: personal access token required to checkout private benchmark repo
    required: true

runs:
  using: 'composite'
  steps:

    ##################################
    # clones repo with different versions of the checkout action, as container has different node versions and some compilers run on older OSs that have differening node versions
    

    - if: ${{ contains(fromJson('["ubuntu:18.04"]'), matrix.OS) }}
      name: checkout v3
      uses: actions/checkout@v3
      with:
        repository: UoB-HPC/simeng-benchmarks
        token: ${{ inputs.PAT }}
        ref: makefile-build-system
        path: simeng-benchmarks

    - if: ${{ !contains(fromJson('["ubuntu:18.04"]'), matrix.OS) }}
      name: checking out benchmark repository
      uses: actions/checkout@v4
      with:
        repository: UoB-HPC/simeng-benchmarks
        ref: makefile-build-system
        token: ${{ inputs.PAT }}
        path: simeng-benchmarks

#    - name: run benchmark
#      shell: bash
#      run: |
#        cd ./simeng-benchmarks/Tools/simulation/validation
#        SIMENG_BENCHMARKS_SRC_DIR=$GITHUB_WORKSPACE/simeng-benchmarks python3 validate_simulation.py all_a64fx.json $GITHUB_WORKSPACE/configs/a64fx.yaml

    - name: CloverLeaf serial gcc8.3.0 armv8.4
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/simeng-benchmarks/Data_Files/CloverLeaf
        $GITHUB_WORKSPACE/simeng-benchmarks/binaries/CloverLeaf/serial/cloverleaf_gcc8.3.0_armv8.4 &> >(tee $GITHUB_WORKSPACE/output.txt)
        grep "This test is considered PASSED" $GITHUB_WORKSPACE/output.txt >> $NUM_INSTANCES
        if $NUM_INSTANCES == 1; then
          exit 1
        fi
        



