name: setup armclang
description: installs dependencies and correct armclang version to build and test simeng

inputs:
  OS:
    description: docker image name
    required: true
  MODE:
    description: simeng-mode e.g. Release or Debug
    required: true
    
runs:
  using: 'composite'
  steps:
    #######################################
    # Install dependencies
    #######################################
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive

        # Update package lists
        apt-get update

        # Install essential packages
        apt-get install -y \
          software-properties-common \
          sudo \
          wget \
          zlib1g-dev \
          python3 \
          build-essential \
          libssl-dev \
          ninja-build \
          tree \
          git

        # add pyparsing for benchmarking
        apt-get install -y python3-pip
        pip3 install pyparsing

        # Add additional repositories
        add-apt-repository universe
        add-apt-repository ppa:ubuntu-toolchain-r/test

        # Update package lists again after adding repositories
        apt-get update

        # Upgrade all installed packages
        apt-get upgrade -y 

    #######################################
    # Install Cmake
    #######################################
    - name: Install cmake via apt
      shell: bash
      run: |
        if [[ ${{ inputs.OS == 'ubuntu:18.04' }} ]]; then
          NAME=bionic
        else
          NAME=focal
        fi

        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
        apt-add-repository "deb https://apt.kitware.com/ubuntu/ $NAME main" && \
        apt update && apt install cmake -y
        apt upgrade -y

    #######################################
    # Install ArmClang
    #######################################
    - name: Install armclang
      shell: bash
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install environment-modules
        source /etc/profile.d/modules.sh

        wget https://developer.arm.com/-/cdn-downloads/permalink/Arm-Compiler-for-Linux/Version_24.04/arm-compiler-for-linux_24.04_Ubuntu-22.04_aarch64.tar
        tar -xf arm-compiler-for-linux_24.04_Ubuntu-22.04_aarch64.tar

        ./arm-compiler-for-linux_24.04_Ubuntu-20.04/arm-compiler-for-linux_24.04_Ubuntu-20.04.sh --install-to ./armclang_compiler
        export MODULEPATH=$MODULEPATH:$(pwd)/armclang_compiler/modulefiles

        module avail
        module load acfl/24.04
        armclang -v
        echo "C_COMPILER=$(which armclang)" >> $GITHUB_ENV
        echo "CPP_COMPILER=$(which armclang++)" >> $GITHUB_ENV

    - name: Build SimEng
      shell: bash
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ inputs.MODE }} -DSIMENG_ENABLE_TESTS=ON -DSIMENG_OPTIMIZE=ON -DCMAKE_C_COMPILER=${{ env.C_COMPILER }} -DCMAKE_CXX_COMPILER=${{ env.CPP_COMPILER }}

        cmake --build build -j $(nproc)

        cmake --build build --target install

      