name: setup gcc
description: installs dependencies and correct gcc version to build and test simeng

inputs:
  OS:
    description: docker image name
    required: true
  MODE:
    description: simeng-mode e.g. Release or Debug
    required: true

runs:
  using: 'composite'
  steps:
    #######################################
    # Install dependencies required (cmake, etc).
    #######################################
    - name: Install dependencies
      shell: bash
      run: |
        dnf -y update && \
        dnf install -y epel-release \
          gcc gcc-c++ make \
          git \
          wget \
          openssl-devel \
          automake \
          autoconf \
          bzip2 \
          file \
          sudo \
          tree \
          zlib-devel

        # add pyparsing for benchmarking
        dnf install -y python3-pip
        pip3 install pyparsing

        dnf group install -y "Development Tools"
        dnf update -y
        dnf upgrade -y

    #######################################
    # Install Cmake
    #######################################
    - name: Install Cmake via DNF
      shell: bash
      run: |
        dnf install -y cmake

    ######################################
    # Install ArmClang
    ######################################
    - name: Install armclang
      shell: bash
      run: |

        dnf install -y environment-modules
        source /etc/profile.d/modules.sh

        wget https://developer.arm.com/-/cdn-downloads/permalink/Arm-Compiler-for-Linux/Version_24.04/arm-compiler-for-linux_24.04_Ubuntu-22.04_aarch64.tar
        tar -xf arm-compiler-for-linux_24.04_Ubuntu-22.04_aarch64.tar

        ./arm-compiler-for-linux_24.04_Ubuntu-20.04/arm-compiler-for-linux_24.04_Ubuntu-20.04.sh --install-to ./armclang_compiler
        export MODULEPATH=$MODULEPATH:$(pwd)/armclang_compiler/modulefiles

        module avail
        module load acfl/24.04
        armclang -v

        echo "C_COMPILER=$(which armclang)" >> $GITHUB_ENV
        echo "CPP_COMPILER=$(which armclang++)" >> $GITHUB_ENV

    #######################################
    # Build SimEng
    #######################################
    - name: Build SimEng
      shell: bash
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ inputs.MODE }} -DSIMENG_ENABLE_TESTS=ON -DSIMENG_OPTIMIZE=ON -DCMAKE_C_COMPILER=${{ env.GCC_DIR }} \
          -DCMAKE_CXX_COMPILER=${{ env.CPP_DIR }}

        cmake --build build -j $(nproc)

        cmake --build build --target install

