---
# The following resources where utilised to create the config file and naming schemes:
# https://github.com/fujitsu/A64FX

Core:
    Simulation-Mode: outoforder
    Clock-Frequency: 3.8
    Timer-Frequency: 100
    Fetch-Block-Size: 32
    Micro-Operations: True
    Vector-Length: 512
Process-Image:
    Heap-Size: 1073741824
    Stack-Size: 1048576
Register-Set:
    GeneralPurpose-Count: 96
    FloatingPoint/SVE-Count: 128
    Predicate-Count: 148
    Conditional-Count: 128
Pipeline-Widths:
    Commit: 8
    Dispatch-Rate: 1
    FrontEnd: 1
    LSQ-Completion: 1
Queue-Sizes:
    ROB: 630
    Load: 130
    Store: 60
Branch-Predictor:
    BTB-bitlength: 11
L1-Cache:
    Access-Latency: 4
    Exclusive: True
    L1 Load Bandwidth: 48
    L1 Store Bandwidth: 64
    Permitted Requests-Per-Cycle: 1
    Permitted-Loads-Per-Cycle: 1
    Permitted-Stores-Per-Cycle: 1
Ports:
    # INT/MEMORY
    0:
        Portname: BR1
        Instruction-Support:
            - BRANCH
    1:
        Portname: BR2
        Instruction-Support:
            - BRANCH
    2:
        Portname: ALU1
        Instruction-Support:
            - INT_SIMPLE
    3:
        Portname: ALU2
        Instruction-Support:
            - INT_SIMPLE
    4:
        Portname: ALU3
        Instruction-Support:
            - INT_SIMPLE
    5:
        Portname: ALU4
        Instruction-Support:
            - INT_SIMPLE
    6:
        Portname: ALU_AND_MUL1
        Instruction-Support:
            - INT_SIMPLE
            - INT_MUL
    7:
        Portname: ALU_AND_MUL2
        Instruction-Support:
            - INT_SIMPLE
            - INT_MUL
    8:
        Portname: IDIV
        Instruction-Support:
            - INT_DIV_OR_SQRT
    9:
        Portname: LD_ST
        Instruction-Support:
            - LOAD
            - STORE
    10:
        Portname: ST
        Instruction-Support:
            - STORE
    11:
        Portname: LD1
        Instruction-Support:
            - LOAD
    12:
        Portname: LD2
        Instruction-Support:
            - LOAD

    ## FP/SIMD
    13:
        Portname: FP_AND_FDIV
        Instruction-Support:
            - FP
            - SVE
            - SCALAR
            - VECTOR
    14:
        Portname: FP_SIMD1
        Instruction-Support:
            - FP_SIMPLE
            - FP_MUL
            - SCALAR
            - VECTOR
            - SVE
    15:
        Portname: FP_SIMD2
        Instruction-Support:
            - FP_SIMPLE
            - FP_MUL
            - SCALAR
            - VECTOR
            - SVE
    16:
        Portname: FP_SIMD3
        Instruction-Support:
            - FP_SIMPLE
            - FP_MUL
            - SCALAR
            - VECTOR
            - SVE

Reservation-Stations:
    0:
        #INT RENAME
        Size: 354
        Ports:
            - BR1
            - BR2
            - ALU1
            - ALU2
            - ALU3
            - ALU4
            - ALU_AND_MUL1
            - ALU_AND_MUL2
            - IDIV
            - LD_ST
            - ST
            - LD1
            - LD2
    1:
        #FP RENAME
        Size: 384
        Ports:
            - FP_AND_FDIV
            - FP_SIMD1
            - FP_SIMD2
            - FP_SIMD3

Execution-Units:
    0:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    1:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    2:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    3:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    4:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    5:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    6:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    7:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    8:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    9:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    10:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    11:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    12:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    13:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    14:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    15:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
    16:
        Pipelined: True
        Blocking-Groups:
            - INT_DIV_OR_SQRT
            - FP_DIV_OR_SQRT
            - SVE_DIV_OR_SQRT
Latencies:
    0:
        Instruction-Groups:
            - INT
        Execution-Latency: 2
        Execution-Throughput: 2
    1:
        Instruction-Groups:
            - INT_SIMPLE_ARTH_NOSHIFT
            - INT_SIMPLE_LOGICAL_NOSHIFT
            - INT_SIMPLE_CVT
        Execution-Latency: 1
        Execution-Throughput: 1
    2:
        Instruction-Groups:
            - INT_MUL
        Execution-Latency: 5
        Execution-Throughput: 1
    3:
        Instruction-Groups:
            - INT_DIV_OR_SQRT
        Execution-Latency: 41
        Execution-Throughput: 41
    4:
        Instruction-Groups:
            - SCALAR_SIMPLE
            - VECTOR_SIMPLE_LOGICAL
            - SVE_SIMPLE_LOGICAL
            - VECTOR_SIMPLE_CMP
            - SVE_SIMPLE_CMP
        Execution-Latency: 4
        Execution-Throughput: 1
    5:
        Instruction-Groups:
            - FP_DIV_OR_SQRT
        Execution-Latency: 29
        Execution-Throughput: 29
    6:
        Instruction-Groups:
            - VECTOR_SIMPLE
            - SVE_SIMPLE
            - SCALAR_SIMPLE_CVT
            - FP_MUL
            - SVE_MUL
        Execution-Latency: 9
        Execution-Throughput: 1
    7:
        Instruction-Groups:
            - SVE_DIV_OR_SQRT
        Execution-Latency: 98
        Execution-Throughput: 98
    8:
        Instruction-Groups:
            - PREDICATE
        Execution-Latency: 3
        Execution-Throughput: 1
    9:
        Instruction-Groups:
            - LOAD_SCALAR
            - LOAD_VECTOR
            - STORE_ADDRESS_SCALAR
            - STORE_ADDRESS_VECTOR
        Execution-Latency: 3
        Execution-Throughput: 1
    10:
        Instruction-Groups:
            - LOAD_SVE
            - STORE_ADDRESS_SVE
        Execution-Latency: 6
        Execution-Throughput: 1
# CPU-Info mainly used to generate a replica of the special (or system) file directory
# structure
CPU-Info:
    # Set Generate-Special-Dir to 'T' to generate the special files directory, or to 'F' to not.
    # (Not generating the special files directory may require the user to copy over files manually)
    Generate-Special-Dir: T
    # Core-Count MUST be 1 as multi-core is not supported at this time. (A64FX true value is 48)
    Core-Count: 1
    # Socket-Count MUST be 1 as multi-socket simulations are not supported at this time. (A64FX true value is 1)
    Socket-Count: 1
    # SMT MUST be 1 as Simultanious-Multi-Threading is not supported at this time. (A64FX true value is 1)
    SMT: 1
    # Below are the values needed to generate /proc/cpuinfo
    BogoMIPS: 200.00
    Features: fp asimd evtstrm sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
    CPU-Implementer: "0x46"
    CPU-Architecture: 8
    CPU-Variant: "0x1"
    CPU-Part: "0x001"
    CPU-Revision: 0
    # Package-Count is used to generate
    # /sys/devices/system/cpu/cpu{0..Core-Count}/topology/{physical_package_id, core_id}
    Package-Count: 1
