#include "A64ExceptionHandler.hh"

#include <iomanip>
#include <iostream>

#include "A64InstructionMetadata.hh"

namespace simeng {

A64ExceptionHandler::A64ExceptionHandler(
    const std::shared_ptr<Instruction>& instruction,
    const ArchitecturalRegisterFileSet& registerFileSet, const char* memory,
    kernel::Linux& linux_)
    : instruction_(*static_cast<A64Instruction*>(instruction.get())),
      registerFileSet_(registerFileSet),
      memory_(memory),
      linux_(linux_) {
  printException(instruction_);
}

bool A64ExceptionHandler::tick() {
  A64InstructionException exception = instruction_.getException();

  if (exception == A64InstructionException::SupervisorCall) {
    uint64_t nextInstructionAddress = instruction_.getInstructionAddress() + 4;
    // Retrieve syscall ID held in register x8
    auto syscallId =
        registerFileSet_.get({A64RegisterType::GENERAL, 8}).get<uint64_t>();
    std::cout << "Syscall ID is " << syscallId << std::endl;

    ProcessStateChange stateChange;
    const Register x0 = {A64RegisterType::GENERAL, 0};
    const Register x1 = {A64RegisterType::GENERAL, 1};
    const Register x2 = {A64RegisterType::GENERAL, 2};
    const Register x3 = {A64RegisterType::GENERAL, 3};
    switch (syscallId) {
      case 78: {  // readlinkat
        const auto dirfd = registerFileSet_.get(x0).get<int64_t>();
        const auto pathnameAddress = registerFileSet_.get(x1).get<uint64_t>();
        const auto bufAddress = registerFileSet_.get(x2).get<uint64_t>();
        const auto bufSize = registerFileSet_.get(x3).get<uint64_t>();

        // Copy string at `pathnameAddress`
        char pathname[kernel::Linux::LINUX_PATH_MAX];
        const char* ptr = memory_ + pathnameAddress;
        size_t i;
        for (i = 0; i < kernel::Linux::LINUX_PATH_MAX; i++) {
          pathname[i] = ptr[i];
          if (ptr[i] == '\0') {
            break;
          }
        }

        if (i == kernel::Linux::LINUX_PATH_MAX) {
          // TODO: Handle LINUX_PATH_MAX case
          std::cout << "Path exceeds LINUX_PATH_MAX" << std::endl;
          return fatal();
        }

        char buffer[kernel::Linux::LINUX_PATH_MAX];
        auto result = linux_.readlinkat(dirfd, pathname, buffer, bufSize);

        if (result < 0) {
          // TODO: Handle error case
          std::cout << "Error generated by readlinkat" << std::endl;
          return fatal();
        }

        auto bytesCopied = static_cast<uint64_t>(result);

        stateChange = {{x0}, {result}};

        // Slice the returned path into <256-byte chunks for writing
        const char* bufPtr = buffer;
        for (i = 0; i < bytesCopied; i += 256) {
          auto size = std::min<uint64_t>(bytesCopied - i, 256ul);
          stateChange.memoryAddresses.push_back({bufAddress + i, size});
          stateChange.memoryAddressValues.push_back(
              RegisterValue(bufPtr, size));
        }
        break;
      }
      case 94: {  // exit_group
        auto exitCode = registerFileSet_.get(x0).get<uint64_t>();
        std::cout << "Received exit_group syscall: terminating with exit code "
                  << exitCode << std::endl;
        return fatal();
      }
      case 160: {  // uname
        const uint64_t base = registerFileSet_.get(x0).get<uint64_t>();
        const uint8_t len =
            65;  // Reserved length of each string field in Linux
        const char sysname[] = "Linux";
        const char nodename[] = "simeng.hpc.cs.bris.ac.uk";
        const char release[] = "0.0.0";
        const char version[] = "#1 SimEng Mon Apr 29 16:28:37 UTC 2019";
        const char machine[] = "aarch64";

        stateChange = {{x0},
                       {static_cast<uint64_t>(0)},
                       {{base, sizeof(sysname)},
                        {base + len, sizeof(nodename)},
                        {base + (len * 2), sizeof(release)},
                        {base + (len * 3), sizeof(version)},
                        {base + (len * 4), sizeof(machine)}},
                       {RegisterValue(sysname), RegisterValue(nodename),
                        RegisterValue(release), RegisterValue(version),
                        RegisterValue(machine)}};
        break;
      }
      case 174:  // getuid
        stateChange = {{x0}, {linux_.getuid()}};
        break;
      case 175:  // geteuid
        stateChange = {{x0}, {linux_.geteuid()}};
        break;
      case 176:  // getgid
        stateChange = {{x0}, {linux_.getgid()}};
        break;
      case 177:  // getegid
        stateChange = {{x0}, {linux_.getegid()}};
        break;
      case 214: {  // brk
        auto result = linux_.brk(registerFileSet_.get(x0).get<uint64_t>());
        stateChange = {{x0}, {static_cast<uint64_t>(result)}};
        break;
      }
      default:
        std::cout << "Unrecognised syscall" << std::endl;
        return fatal();
    }

    std::cout << "Resuming from 0x" << std::hex << nextInstructionAddress
              << std::dec << "\n"
              << std::endl;

    result_ = {false, nextInstructionAddress, stateChange};
    return true;
  }

  return fatal();
}

const ExceptionResult& A64ExceptionHandler::getResult() const {
  return result_;
}

void A64ExceptionHandler::printException(const A64Instruction& insn) const {
  auto exception = insn.getException();
  std::cout << "Encountered ";
  switch (exception) {
    case A64InstructionException::EncodingUnallocated:
      std::cout << "illegal instruction";
      break;
    case A64InstructionException::ExecutionNotYetImplemented:
      std::cout << "execution not-yet-implemented";
      break;
    case A64InstructionException::SupervisorCall:
      std::cout << "supervisor call";
      break;
    case A64InstructionException::HypervisorCall:
      std::cout << "hypervisor call";
      break;
    case A64InstructionException::SecureMonitorCall:
      std::cout << "secure monitor call";
      break;
    default:
      std::cout << "unknown (id: " << static_cast<unsigned int>(exception)
                << ")";
  }
  std::cout << " exception\n";

  std::cout << "  Generated by instruction: \n"
            << "    0x" << std::hex << std::setfill('0') << std::setw(16)
            << insn.getInstructionAddress() << ": ";

  auto& metadata = insn.getMetadata();
  for (uint8_t byte : metadata.encoding) {
    std::cout << std::setfill('0') << std::setw(2)
              << static_cast<unsigned int>(byte) << " ";
  }
  std::cout << std::dec << "    ";
  if (exception == A64InstructionException::EncodingUnallocated) {
    std::cout << "<unknown>";
  } else {
    std::cout << metadata.mnemonic << " " << metadata.operandStr;
  }
  std::cout << "\n      opcode ID: " << metadata.opcode;
  std::cout << std::endl;
}

bool A64ExceptionHandler::fatal() {
  result_ = {true, 0, {}};
  return true;
}

}  // namespace simeng
