#ifndef VERSION_H_INCLUDED
#define VERSION_H_INCLUDED

#define SIMENG_VERSION "0.9.4"
#define SIMENG_COMPILE_OPTIONS "-Wall;$<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>"
#define SIMENG_COMPILE_DEFINITIONS "SIMENG_COMPILE_DEFINITIONS-NOTFOUND"
#define SIMENG_BUILD_TYPE "Debug"
#define SIMENG_SOURCE_DIR "/home/rahat/work/src/SimEng"
#define SIMENG_LLVM_VERSION 14
#define SIMENG_ENABLE_TESTS "1"
#define SIMENG_BUILD_DIR "/home/rahat/work/src/SimEng/build"

#endif
