#include "simeng/config/SimInfo.hh"

namespace simeng {
namespace config {

/** A getter function to retrieve the ryml::Tree representing the underlying
 * model config file. */
ryml::ConstNodeRef SimInfo::getConfig() {
  return getInstance()->validatedConfig_.crootref();
}

/** A setter function to set the model config file from a path to a YAML file.
 */
void SimInfo::setConfig(std::string path) { getInstance()->makeConfig(path); }

/** A function to add additional config values to the model config file. */
void SimInfo::addToConfig(std::string configAdditions) {
  getInstance()->mdlCnf_.addConfigOptions(configAdditions);
  // Replace the validated config with new instance with the supplied
  // additional values
  getInstance()->validatedConfig_ = getInstance()->mdlCnf_.getConfig();
  // Update previously extracted values from the config file
  getInstance()->extractValues();
}

/** A function to generate a default config file based on a passed ISA. */
void SimInfo::generateDefault(ISA isa, bool force) {
  if (isa == config::ISA::AArch64)
    getInstance()->mdlCnf_.reGenerateDefault(ISA::AArch64, force);
  else if (isa == config::ISA::RV64)
    getInstance()->mdlCnf_.reGenerateDefault(ISA::RV64, force);

  // Update config path to be the default string
  getInstance()->setConfigPath(DEFAULT_STR);

  // Replace the validated config with the new default config
  getInstance()->validatedConfig_ = getInstance()->mdlCnf_.getConfig();
  // Update previously extracted values from the config file
  getInstance()->extractValues();
}

/** A getter function to retrieve the config file path. */
std::string SimInfo::getConfigPath() { return getInstance()->configFilePath_; }

/** A setter function to set the config file path. */
std::string SimInfo::setConfigPath(std::string path) {
  return getInstance()->configFilePath_ = path;
}

/** A getter function to retrieve the simulation mode of the current SimEng
 * instance. */
simMode SimInfo::getSimMode() { return getInstance()->mode_; }

/** A getter function to retrieve the simulation mode of the current SimEng
 * instance as a string. */
std::string SimInfo::getSimModeStr() { return getInstance()->modeStr_; }

/** A getter function to retrieve which ISA the current simulation is using.
 */
ISA SimInfo::getISA() { return getInstance()->isa_; }

/** A getter function to retrieve a vector of {size, number} pairs describing
 * the available architectural registers. */
const std::vector<simeng::RegisterFileStructure>& SimInfo::getArchRegStruct() {
  return getInstance()->archRegStruct_;
}

/** A getter function to retrieve a vector of Capstone sysreg enums for
 * all the system registers that should be utilised in simulation. */
const std::vector<uint64_t>& SimInfo::getSysRegVec() {
  return getInstance()->sysRegisterEnums_;
}

/** A getter function to retrieve an index of a Capstone sysreg enum
 * within the sysRegisterEnums_ vector. */
uint32_t SimInfo::getSysRegVecIndex(uint64_t sysReg) {
  auto sysRegVec = getInstance()->sysRegisterEnums_;
  auto regItr = std::find(sysRegVec.begin(), sysRegVec.end(), sysReg);
  assert(regItr != sysRegVec.end() &&
         "[SimEng:SimInfo] System register was not defined in the System "
         "Register Vector. Please ensure it is included in "
         "config::SimInfo::sysRegisterEnums_.");
  return regItr - sysRegVec.begin();
}

/** A getter function to retrieve whether or not the special files
 * directories should be generated. */
const bool SimInfo::getGenSpecFiles() {
  return getInstance()->genSpecialFiles_;
}

/** A function used to reset the architectural register file structure. */
void SimInfo::resetArchRegs() { getInstance()->resetArchRegStruct(); }

SimInfo::SimInfo() {
  // Set the validated config file to be the current default config
  // generated by the default constructor of ModelConfig
  validatedConfig_ = mdlCnf_.getConfig();
  extractValues();
}

/** Gets the  instance of the SimInfo class. */
std::unique_ptr<SimInfo>& SimInfo::getInstance() {
  static std::unique_ptr<SimInfo> SimInfoClass = nullptr;
  if (SimInfoClass == nullptr) {
    SimInfoClass = std::unique_ptr<SimInfo>(new SimInfo());
  }
  return SimInfoClass;
}

/** Create a model config from a passed YAML file path. */
void SimInfo::makeConfig(std::string path) {
  // Recreate the model config instance from the YAML file path
  mdlCnf_ = simeng::config::ModelConfig(path);

  // Update config path to be the passed path
  configFilePath_ = path;

  // Update the validated config file
  validatedConfig_ = mdlCnf_.getConfig();
  extractValues();
}

/** A function to extract various values from the generated config file to
 * populate frequently queried model config values. */
void SimInfo::extractValues() {
  // Get ISA type and set the corresponding architectural fileset
  std::string isa;
  validatedConfig_["Core"]["ISA"] >> isa;
  if (isa == "AArch64") {
    isa_ = config::ISA::AArch64;
    // Define system registers
    sysRegisterEnums_ = {arm64_sysreg::ARM64_SYSREG_DCZID_EL0,
                         arm64_sysreg::ARM64_SYSREG_FPCR,
                         arm64_sysreg::ARM64_SYSREG_FPSR,
                         arm64_sysreg::ARM64_SYSREG_TPIDR_EL0,
                         arm64_sysreg::ARM64_SYSREG_MIDR_EL1,
                         arm64_sysreg::ARM64_SYSREG_CNTFRQ_EL0,
                         arm64_sysreg::ARM64_SYSREG_CNTVCT_EL0,
                         arm64_sysreg::ARM64_SYSREG_PMCCNTR_EL0,
                         arm64_sysreg::ARM64_SYSREG_SVCR};
  } else if (isa == "rv64") {
    isa_ = config::ISA::RV64;
    // Define system registers
    sysRegisterEnums_ = {0x001, 0x002, 0x003, 0xC00, 0xC01, 0xC02};
  }

  // Initialise architectural reg structures by using the reset
  // functionality
  resetArchRegStruct();

  // Get Simulation mode
  std::string mode;
  validatedConfig_["Core"]["Simulation-Mode"] >> mode;
  if (mode == "emulation") {
    mode_ = config::simMode::emulation;
    modeStr_ = "Emulation";
  } else if (mode == "inorderpipelined") {
    mode_ = config::simMode::inorder;
    modeStr_ = "In-Order Pipelined";
  } else if (mode == "outoforder") {
    mode_ = config::simMode::outoforder;
    modeStr_ = "Out-of-Order";
  }

  // Get if the special files directory should be created
  validatedConfig_["CPU-Info"]["Generate-Special-Dir"] >> genSpecialFiles_;
}

/** Function used to reset the architectural register file structure. */
void SimInfo::resetArchRegStruct() {
  // Given some register quantities rely on Config file arguments (SME
  // relies on SVL), it is possible that if the config was to change the
  // register quantities would be incorrect. This function provides a way to
  // reset the Architectural register structure.
  if (isa_ == config::ISA::AArch64) {
    uint16_t numSysRegs = static_cast<uint16_t>(sysRegisterEnums_.size());
    // Set the size of SME ZA in bytes by dividing the SVL by 8
    uint16_t ZAbits;
    validatedConfig_["Core"]["Streaming-Vector-Length"] >> ZAbits;
    const uint16_t ZAsize = ZAbits / 8;
    archRegStruct_ = {
        {8, 32},          // General purpose
        {256, 32},        // Vector
        {32, 17},         // Predicate
        {1, 1},           // NZCV
        {8, numSysRegs},  // System
        {256, ZAsize},    // Matrix (Each row is a register)
    };
  } else if (isa_ == config::ISA::RV64) {
    uint16_t numSysRegs = static_cast<uint16_t>(sysRegisterEnums_.size());
    archRegStruct_ = {
        {8, 32},          // General purpose
        {8, 32},          // Floating Point
        {8, numSysRegs},  // System
    };
  }
}

}  // namespace config
}  // namespace simeng